### ISSUE TITLE
tasks to finish 4.2 support

### ISSUE THREAD

**Issue by kares** [jruby/activerecord-jdbc-adapter#599]
- [x] getting `cast_type` around in Column instances
 * [x] for MySQL/Postgres/SQLite based on AR code
 * [x] get `type_cast` working with Derby: #662
 * [x] getting it to work with others (H2/HSQLDB etc.)
 * [x] types should work with generic **adapter: jdbc**
- [x] ~~`_string_to_time` emulation on our 1.3.x line (for custom selects e.g. `SELECT now()`)~~
- [x] truncate support (4 all) https://github.com/rails/rails/commit/9a4e183fe9f8
- [ ] review which of the supported adapters can support bigint (besides postgres https://github.com/rails/rails/commit/574234be06) 3c01353a6258
- [x] generalize (share) columns 4.2 detection https://github.com/prathamesh-sonpatki/activerecord-jdbc-adapter/commit/cc6b487fc
- [x] Column.new has new `cast_type` param https://github.com/rails/rails/commit/4bd5dffc85a4f3a660
  * [x] likely will need to be passed around for other custom `Column`s in a backward-compatible way
- [x] Column `type_cast` needs to be reviewed 4 all adapters https://github.com/rails/rails/commit/e781aa31fc52a
- [x] need to check and avoid double loading (e.g. **postgresql/array_parser.rb**)
- [x] removed `primary` method rails/rails@05dd3df (see #609)
  * [x] oracle depends on `column.primary` in `prefetch_primary_key?`
  * [x] firebird depends on `column.primary` in `prefetch_primary_key?`
  * [x] ~~db2 depends on `column.primary` (but only in quote - should be fajn)~~
  * [x] mssql depends on `column.primary` in `determine_order_clause`
- [x] [postgres] backport bit quoting https://github.com/rails/rails/commit/d5411fb37ca9a35f49a5
- [x] [postgres] test XML quoting https://github.com/rails/rails/commit/f6968bd601e38fb506
- [x] [postgres] [bigserial PK support](https://github.com/jruby/activerecord-jdbc-adapter/issues/632) https://github.com/rails/rails/commit/6dc178711de036a
- [x] handle serialized attributes (esp. for all adapters using callbacks for lobs - Oracle, DB2, ...)
- [x] native (base) foreign_keys impl using JDBC API

... [fix remaining/reported 4.2 bugs](https://github.com/jruby/activerecord-jdbc-adapter/labels/rails-4.2) (besides getting the test suite green 4 all)

====
you can support AR 4.2 support at [BountySource](https://www.bountysource.com/issues/5831191-tasks-to-finish-4-2-support)

**Comment by waynerobinson** [comment]
I'd just like to mention that I've added a $100 bounty to this project on BountySouce. 
https://www.bountysource.com/issues/5831191-tasks-to-finish-4-2-support

**Comment by kevinrood** [comment]
Any further news on progress toward Rails 4.2 compatability?

**Comment by Seliestel** [comment]
Please note that the uuid native postgres type is not supported in the 4.2 version of the adapter. It works fine with 4.0 though. Many thanks for working on this!

**Comment by langesi** [comment]
I've added a bounty of 250USD to the project

**Comment by Ch4s3** [comment]
Added another $15 and sent the bounty around on my social medias.

**Comment by saveav** [comment]
JRuby-based Rails 4.2 unable to let gem to generate model for us. For example, Remexify gem (and also Devise) were unable of generating model from scratch through its generate command.

**Comment by Ch4s3** [comment]
@kares What's left on this? It looks like https://github.com/jruby/activerecord-jdbc-adapter/issues/632 was closed finishing `[postgres] bigserial PK support rails/rails@6dc1787`, and maybe type_cast for postgres.

**Comment by kares** [comment]
we're working on it ... it still might need a week or two to get pass (hopefully most) supported adapters.

**Comment by Ch4s3** [comment]
Oh awesome. Need help testing anything?

**Comment by kares** [comment]
@Ch4s3 you could run against our **1-3-stable** branch as it's already (and still expected) to be updated.
we'll mostly need non-mysql/pg/sqlite testers later ... oracle, db2, hsqldb, h2 maybe ms-sql and firebird
... but its likely we won't cover all (thoroughly) since its just too much to handle on our own ...

**Comment by Ch4s3** [comment]
Ok, so 1-3-stable seems to work fine with jRuby 9000, Rails 4.2.3 for may app. I ran rake db:reset and a bunch of Postgres heavy rspec tests.

**Comment by donv** [comment]
@kares Should we close this now?  AR 4.2 is now supported on all but the special adapters:  oracle, db2, firebird, and mssql.  We could track these in separat issues, and only emit the AR 4.2 warning for these adapters.

**Comment by kares** [comment]
do not see a reason why we should split it for a "few left" at least until a review is done. would prefer to keep the warning until the generic jdbc case handles type resolution to at least some degree (like it used to on pre 4.2) - travis-ci fully green ... think we're close but there's no need to rush it up. the hard work will be mostly about supporting bug reports anyways.

**Comment by Ch4s3** [comment]
:+1:

**Comment by kares** [comment]
after **1.3.17** that included a lot of AR 4.2 compatibility improvements, mostly for MySQL/PostgreSQL as well as the generic JDBC adapter, in [**1.3.18**](https://github.com/jruby/activerecord-jdbc-adapter/releases/tag/v1.3.18) literally all adapters have been reviewed to support AR 4.2 to around the same extent as they handle previous AR versions ... some of course need real-world usage to confirm thus warnings are left on Oracle/DB2/MSSQL despite support being there. also worth mentioning that generic **adapter: jdbc** and AR-JDBC extension gems should have an easier job of handling changes such as the 'new' `AR::Type` system since **1.3.18**
